version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: maxflow-db
    environment:
      POSTGRES_USER: maxflow_user
      POSTGRES_PASSWORD: maxflow_pass
      POSTGRES_DB: maxflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: maxflow-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/maxflow
      SPRING_DATASOURCE_USERNAME: maxflow_user
      SPRING_DATASOURCE_PASSWORD: maxflow_pass

  frontend:
    build: ./frontend
    container_name: maxflow-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
